version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    working_dir: /usr/src/app
    volumes:
      - django_static_volume:/usr/src/app/static
      - django_media_volume:/usr/src/app/media
    restart: always
    
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    env_file:
      - ./backend/.env
    networks:
      - clicker-network

  db:
    image: postgres:17-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - clicker-network
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose: 
      - 5432

  nginx:
      build: ./nginx
      container_name: nginx
      networks:
        - clicker-network
      ports:
        - 80:80
      depends_on:
        - backend
      env_file:
        - ./backend/.env
      environment:
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - REDIS_USER=${REDIS_USER}
      volumes:
        - django_static_volume:/usr/src/app/static
        - django_media_volume:/usr/src/app/media 
        - ./nginx:/etc/nginx/conf.d
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - clicker-network

    
volumes:
  postgres_data:
  django_static_volume: 
  django_media_volume:
  redis_data:

networks:
  clicker-network:
    driver: bridge