FROM python:3.12-slim

WORKDIR /usr/src/app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY . /usr/src/app

RUN uv sync --group prod --frozen --no-cache
ENV PATH="/usr/src/app/.venv/bin:$PATH"
EXPOSE 8080

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]